### ISSUE TITLE
Not sending SMS

### ISSUE THREAD

**Issue by olivier-nexmo** [Nexmo/node-voice-proxy#6]
I don't think the code is doing an NI check for Virtual Numbers, so:

this.nexmo.message.sendSms(conversation.userB.virtualNumber.**msisdn**,conversation.userA.realNumber.msisdn,'Call this number to talk to UserB');

and 

this.nexmo.message.sendSms(conversation.userA.virtualNumber.**msisdn**,conversation.userB.realNumber.msisdn,'Call this number to talk to UserB');

should be changed to:

this.nexmo.message.sendSms(conversation.userB.virtualNumber,conversation.userA.realNumber.msisdn,'Call this number to talk to UserB');

and 

this.nexmo.message.sendSms(conversation.userA.virtualNumber,conversation.userB.realNumber.msisdn,'Call this number to talk to UserB');

(the conversation.userX.virtualNumber object doesn't have a msisdn property therefore the call to the Message class to send an SMS is failing and msisdn is 'undefined')

**Comment by leggetter** [comment]
[The code](https://github.com/Nexmo/node-voice-proxy/blob/master/lib/VoiceProxy.js#L107-L112) does do a Number Insight check at a basic level when a [conversation is created](https://github.com/Nexmo/node-voice-proxy/blob/master/lib/VoiceProxy.js#L92).

As per https://github.com/Nexmo/node-voice-proxy/pull/7/files#diff-04c6e90faac2675aa89e2176d2eec7d8R42 the format of the `PROVISIONED_NUMBERS` should have a `msisdn`.

I've just had this running locally so can't find any problems.
