### ISSUE TITLE
Conversations cannot be found when presenting a phone number with '+' prefix e.g. +44

### ISSUE THREAD

**Issue by jonlingard** [Nexmo/node-voice-proxy#9]
Hi, I tried this today and provisioned virtual UK landline numbers (44203*) for the proxy calls

I got the following error when i tried a proxy call (numbers masked to protect the innocent..)

"Error: No conversation found from: +447956xxxxxx to: 442039xxxxxx"

I then changed the virtual numbers to UK Mobile numbers (447*) and it works ok

is it possible that if the carrier presents a '+' CLI that the app would fail to match the numbers?

**Comment by leggetter** [comment]
After the numbers are input:

* The numbers are checked via [Number Insight](https://docs.nexmo.com/number-insight)
* Saved as a conversation

Part of doing the number insight operation will bring the number back without the `+` so a number prefixed with `+44` will brought back as just `44...`.

You can see the code for this here:
https://github.com/Nexmo/node-voice-proxy/blob/38bb5c04d1b23599f0a36e8627edf1e544ea8fe3/lib/VoiceProxy.js#L93-L143

Closing the issue - but feel free to ask any further questions about this.

**Comment by jonlingard** [comment]
The NI part works, and the conversation is setup ok, and the SMS is sent out to both parties, but then when you call the number to proxy the call it reports the error.

Conversation:

[{"userA":{"realNumber":{"msisdn":"447956xxxxxx","country":"GB"},"virtualNumber":{"country":"GB","msisdn":"442039xxxxxx"}},"userB":{"realNumber":{"msisdn":"447971xxxxxx","country":"GB"},"virtualNumber":{"country":"GB","msisdn":"442039xxxxxx"}}}]

userA calls userB:

"Error: No conversation found from: +447956xxxxxx to: 442039xxxxxx"

- note the error has the + on only one of the numbers, Conversation above has no +

NOTE: This is only when the LVN's are landlines, when switched to Mobile LVN's it works just fine

**Comment by leggetter** [comment]
@jonlingard The carrier should not provide numbers with a `+` prefix. Worth checking with support, but I believe if that does happen then it's a mistake by the carrier network.
